export const welcome = {
    title: 'WELCOME',
    type: 'message',
    content: [
        'WELCOME TO NULLROUTE, OPERATOR.',
        '',
        'BEFORE WE SET YOU LOOSE, WE NEED TO ENSURE YOU KNOW WHAT YOU\'RE DOING.',
        '',
        'YOU\'LL FIND A SIMPLE CONTRACT IN YOUR INBOX.',
        '',
        'ONCE YOU COMPLETE THE CONTRACT WE\'LL GIVE YOU TIER 1 CLEARANCE.',
        '',
        'AFTER THAT, CONNECT TO NULLROUTE.',
        'YOU\'LL FIND CONTRACTS ON THE BOARD THERE.',
        '',
        'GOOD LUCK.',
        '',
        '- NIX',
    ],
};

export const initContract = {
    title: 'INIT',
    type: 'story-contract',
    content: [
        'PROVE TO US YOU CAN DO THE SIMPLEST OF TASKS',
        '',
        'CONNECT TO THE NULLROUTE TEST MACHINE AT \'10.0.0.8\'',
        '',
        'THEN DELETE THE FILE TITLED: \'DELETE_ME.txt\'',
        '',
        'REWARD: TIER 1 CLEARANCE',
        'DIFFICULTY: 0',
        '',
        'IT\'LL BE EASY.',
        '',
        '- ASH',
    ],
};

export const friend = {
    title: 'HELLOWORLD',
    type: 'message',
    content: [
        'HELLO, FELLOW OPERATOR!',
        '',
        'YOU\'RE NEW HERE, SO LET ME INTRODUCE MYSELF.',
        '',
        'I\'M FROST. I\'VE BEEN AROUND THE NET, SO I KNOW HOW IT FEELS JUST STARTING OUT.',
        '',
        'IF YOU NEED ANYTHING - INTEL, ADVICE, ANYTHING - MY INBOX IS OPEN.',
        '',
        'NOT LIKE YOU\'LL GET MUCH HELP FROM ANYONE ELSE AROUND HERE...',
        '',
        'JUST, BE CAREFUL. DON\'T GET TRACED.',
        '',
        'STAY SHARP.',
        '',
        '- FROST'
    ],
}

export const nixReportAshOne = {
    title: 'ASH REPORT #8',
    type: 'nix-message',
    content: [
        '',
        'RELAY NODE HANDLER: [ OK ]',
        'A.D.M.N GRID: [ ONLINE ]',
        'CONTRACT MODULE: [ UP ]',
        '',
        '[ ALL SYSTEMS NOMINAL ]',
        '',
        'MESSAGE FROM ADMIN [ ASH ]:',
        '',
        'RAN THE SCAN YOU REQUESTED, I STILL DON\'T SEE WHY I HAVE TO KEEP DOING THIS.',
        '',
        'IS THIS ABOUT YOUR NEW PROJECT?',
        '',
        'IF YOU DON\'T WANT TO TELL US WHAT IT IS THAT\'S FINE.',
        '',
        'JUST DON\'T ACCIDENTLY BRING THE WHOLE SYSTEM DOWN, PEOPLE RELY ON THIS.',
        '',
        'PEOPLE LIKE ME.',
        '',
        '- ASH',
    ],
}

export const nixReportEmberOne = {
    title: 'EMBER REPORT #3',
    type: 'nix-message',
    content: [
        '',
        'CHECKED OUT THE OPERATORS ON THAT LIST YOU SENT ME,',
        '',
        'I HAVE TO SAY IT\'S HARD GETTING INTEL ON A SYSTEM DESGINED FOR ANONYMITY.',
        '',
        'ANYWAY, HERE\'S THE RUNDOWN:',
        '',
        'VOID [ NR-0024 ]: NODE ACTIVE 423 DAYS AGO',
        '',
        'NULL [ NR-0037 ]: NODE ACTIVE 58 DAYS AGO',
        '',
        'ZERO [ NR-0049]: NODE ACTIVE 632 DAYS AGO',
        '',
        'FROST [ NR-0052 ]: NODE ACTIVE 1 DAY AGO',
        '',
        'DON\'T KNOW WHAT YOU NEED THIS FOR, BUT YOU\'RE THE BOSS.',
        '',
        '- EMBER',
    ],
}

export const nixMessageIgnis = {
    title: 'CONCERNS',
    type: 'nix-message',
    content: [
        '',
        'NIX,',
        '',
        'I\'VE NOTICED YOU\'VE STARTED DISTANCING YOURSELF FROM EVERYONE.',
        '',
        'ALL WE HEAR FROM YOU NOW IS DIRECTIONS FOR TASKS WE MUST COMPLETE.',
        'NULLROUTE ISN\'T THE SAME WITHOUT YOU.',
        '',
        'WE KNOW YOU\'RE WORKING ON SOMETHING, LET US HELP.',
        'IT CAN\'T BE GOOD FOR YOU TO KEEP GOING LIKE THIS.',
        '',
        'THINK ABOUT IT.',
        '',
        '- PYRE',
    ],
}

export const spam = [
    {
        title: 'FREE TOOLS',
        type: 'message',
        content: [
            'HEY OPERATOR,',
            '',
            'TIRED OF SLOW TOOLS? WE\'VE GOT THE LATEST CRACKWARE.',
            '',
            'PORTSCAN V5. PASSCRACK V5. ALL FREE.',
            '',
            'JUST CONNECT TO 198.51.100.4 AND DOWNLOAD.',
            '',
            'NO STRINGS ATTACHED.',
            '',
            '- TOTALLY LEGIT GUY',
        ],
    },
    {
        title: 'URGENT',
        type: 'message',
        content: [
            'OPERATOR.',
            '',
            'YOUR NODE HAS BEEN FLAGGED.',
            '',
            'YOU MUST VERIFY YOUR CREDENTIALS IMMEDIATELY.',
            '',
            'CONNECT TO 198.51.100.9 AND SUBMIT YOUR HANDLE AND PASSWORD.',
            '',
            'FAILURE TO COMPLY WILL RESULT IN ACCOUNT TERMINATION.',
            '',
            '- NULLROUTE ADMIN',
        ],
    },
    {
        title: 'BIG MONEY',
        type: 'message',
        content: [
            'WANT TO MAKE 50,000 CR IN ONE JOB?',
            '',
            'WE HAVE A CONTRACT THAT PAYS MORE THAN NULLROUTE EVER WILL.',
            '',
            'NO CLEARANCE REQUIRED. NO QUESTIONS ASKED.',
            '',
            'REPLY TO THIS MESSAGE WITH YOUR NODE ADDRESS TO GET STARTED.',
            '',
            '- ANONYMOUS',
        ],
    },
    {
        title: 'OLD FRIEND',
        type: 'message',
        content: [
            'HEY,',
            '',
            'NOT SURE IF THIS IS THE RIGHT ADDRESS.',
            '',
            'IT\'S CIPHER. WE WORKED TOGETHER ON THE DELTA JOB TWO YEARS BACK.',
            '',
            'IF THIS IS YOU, YOU KNOW WHERE TO FIND ME.',
            '',
            'IF IT\'S NOT, FORGET YOU SAW THIS.',
            '',
            '- C',
        ],
    },
    {
        title: 'WARNING',
        type: 'message',
        content: [
            'OPERATOR.',
            '',
            'YOU\'VE BEEN NOTICED.',
            '',
            'I WON\'T SAY BY WHO. BUT THEY\'RE WATCHING YOUR NODE.',
            '',
            'CLEAN YOUR LOGS. CHANGE YOUR ROUTE.',
            '',
            'DON\'T ASK WHO THIS IS.',
            '',
            '- UNKNOWN',
        ],
    },
    {
        title: 'UPGRADE',
        type: 'message',
        content: [
            'OPERATOR,',
            '',
            'SELLING A CRUX ALPHA-300 CPU. BARELY USED.',
            '',
            'ASKING 8,000 CR. FIRM.',
            '',
            'FIRST COME FIRST SERVED.',
            '',
            'SERIOUS INQUIRIES ONLY.',
            '',
            '- VENDOR_77',
        ],
    },
    {
        title: 'JOIN US',
        type: 'message',
        content: [
            'WE ARE PHANTOM CIRCUIT.',
            '',
            'WE OPERATE OUTSIDE THE GRID. NO BROKERS. NO MIDDLEMEN.',
            '',
            'IF YOU\'RE TIRED OF WORKING FOR CREDITS THAT SOMEONE ELSE DECIDED YOU DESERVED,',
            'WE HAVE A DIFFERENT OFFER.',
            '',
            'FIND US IF YOU\'RE INTERESTED.',
            '',
            '- PHANTOM CIRCUIT',
        ],
    },
    {
        title: 'NICE RIG',
        type: 'message',
        content: [
            'HEY NEW BLOOD,',
            '',
            'SAW YOUR NODE COME ONLINE.',
            '',
            'KEMTEC 80486DX? SERIOUSLY?',
            '',
            'YOU\'RE GOING TO GET TRACED IN ABOUT THIRTY SECONDS WITH THAT THING.',
            '',
            'GOOD LUCK OUT THERE. YOU\'LL NEED IT.',
            '',
            '- RAZOR',
        ],
    },
    {
        title: 'DEAL',
        type: 'message',
        content: [
            'LISTEN,',
            '',
            'I HAVE INTEL ON THREE TIER 4 TARGETS.',
            '',
            'IPS, SECURITY LAYOUTS, THE WORKS.',
            '',
            'PRICE: 2,000 CR.',
            '',
            'INTERESTED? YOU KNOW WHERE TO FIND ME.',
            '',
            '- GHOST_MKT',
        ],
    },
    {
        title: 'HI',
        type: 'message',
        content: [
            'HI.',
            '',
            'WRONG ADDRESS. IGNORE THIS.',
            '',
            '- NOBODY',
        ],
    },
    {
        title: 'BOUNTY',
        type: 'message',
        content: [
            'ATTENTION ALL OPERATORS.',
            '',
            'BOUNTY POSTED: 15,000 CR FOR INFORMATION LEADING TO THE IDENTIFICATION',
            'OF THE OPERATOR KNOWN AS SPECTER.',
            '',
            'LAST SEEN ON THE A.D.M.N. GRID. TIER 8 CLEARANCE.',
            '',
            'REPLY THROUGH SECURE CHANNEL ONLY.',
            '',
            '- IRONWALL SECURITIES',
        ],
    },
    {
        title: 'NETWORK DOWN',
        type: 'message',
        content: [
            'HEADS UP.',
            '',
            'SECTOR 7 RELAY NODES ARE DOWN.',
            '',
            'IF YOUR ROUTE GOES THROUGH THAT SECTOR, REROUTE NOW.',
            '',
            'NOT SURE WHEN THEY\'LL BE BACK UP. COULD BE HOURS.',
            '',
            '- GRID_MONITOR',
        ],
    },
    {
        title: 'GOOD JOB',
        type: 'message',
        content: [
            'DON\'T KNOW WHO YOU ARE.',
            '',
            'BUT SOMEONE HIT MERIDIAN TRANSIT LAST NIGHT AND IT WASN\'T SLOPPY.',
            '',
            'WHOEVER IT WAS KNEW WHAT THEY WERE DOING.',
            '',
            'JUST WANTED TO SAY: GOOD JOB.',
            '',
            '- ANONYMOUS',
        ],
    },
    {
        title: 'OFFER',
        type: 'message',
        content: [
            'OPERATOR.',
            '',
            'MY CLIENT IS LOOKING FOR SOMEONE DISCREET.',
            '',
            'THE JOB ISN\'T ON ANY BOARD. IT NEVER WILL BE.',
            '',
            'PAYOUT IS SIGNIFICANT. RISK IS... ALSO SIGNIFICANT.',
            '',
            'IF YOU\'RE INTERESTED, YOU\'LL KNOW HOW TO FIND ME.',
            '',
            '- BROKER_X',
        ],
    },
    {
        title: 'REMINDER',
        type: 'message',
        content: [
            'THIS IS AN AUTOMATED REMINDER.',
            '',
            'YOUR TRACE BUFFER SUBSCRIPTION EXPIRES IN 3 DAYS.',
            '',
            'FAILURE TO RENEW WILL RESULT IN REDUCED BUFFER CAPACITY.',
            '',
            'THIS MESSAGE WAS SENT IN ERROR.',
            '',
            '- AUTOMATED SYSTEM',
        ],
    },
];