export const lines = [
  { text: 'BIOS v2.31.04 — CRESTFIELD SYSTEMS' },
  { text: '' }, // blank line
  { text: 'COPYRIGHT (C) 1987-1994 C.O.R.E. HARDWARE DIVISION' },
  { text: 'ALL RIGHTS RESERVED.' },
  { text: '' },
  { text: 'PERFORMING POST', dots: true },
  { text: '' },
  { text: '   MEM:', value: '[ 640K OK ]', dots: false },
  { text: '   EXTENDED MEM:', value: '[ 8192K OK ]', dots: false },
  { text: '   SHADOW RAM:', value: '[ ENABLED ]', dots: false },
  { text: '' },
  { text: '   CPU: KEMTEC 80486DX @ 33MHZ' },
  { text: '   FPU: NOT DETECTED' },
  { text: '' },
  { text: 'INITIALISING SYS BUS', dots: true, ok: true },
  { text: 'CHECKING DMA CONTROLLERS', dots: true, ok: true },
  { text: 'CHECKING INTERRUPT CONTROLLERS', dots: true, ok: true },
  { text: 'VERIFYING CMOS CHECKSUM', dots: true, ok: true },
  { text: 'DETECTING PRIMARY DRIVES', dots: true },
  { text: '   DRIVE 0: NORSTORE NS-251 (80MB)', dots: true, ok: true },
  { text: '   DRIVE 1: NOT DETECTED' },
  { text: 'INITIALISING VIDEO ADAPTER', dots: true, ok: true },
  { text: '' },
  { text: 'LOADING CORE OS V4.7.1', dots: true },
  { text: '   DECOMPRESSING KERNEL IMAGE', dots: true, ok: true },
  { text: '   MOUNTING ROOT FILESYSTEM', dots: true, ok: true },
  { text: '   CHECKING DISK INTEGRITY', dots: true, ok: true },
  { text: '   LOADING DEVICE DRIVERS', dots: true },
  { text: '      /DEV/TTY0', ok: true },
  { text: '      /DEV/TTY1', ok: true },
  { text: '      /DEV/NULL', ok: true },
  { text: '      /DEV/MEM', ok: true },
  { text: '      /DEV/HDA', ok: true },
  { text: 'STARTING SYSTEM CLOCK', dots: true, ok: true },
  { text: 'SYNCHRONISING WITH NTP SERVER', dots: true, ok: true },
  { text: 'INITIALISING NETWORK STACK', dots: true, ok: true },
  { text: 'ASSIGNING NODE ADDRESS: 127.0.0.1' },
  { text: 'REGISTERING WITH A.D.M.N. GRID', dots: true, ok: true },
  { text: '' },
  { text: 'INITIALISING MEMORY MANAGEMENT UNIT', dots: true, ok: true },
  { text: '   MAPPING KERNEL PAGES', dots: true, ok: true },
  { text: '   SETTING UP PAGE TABLES', dots: true, ok: true },
  { text: '   ENABLING VIRTUAL ADDRESSING', dots: true, ok: true },
  { text: 'CALIBRATING SYSTEM TIMER', dots: true, ok: true },
  { text: 'INITIALISING INTERRUPT HANDLER', dots: true, ok: true },
  { text: '   IRQ0: SYSTEM TIMER', ok: true },
  { text: '   IRQ1: KEYBOARD CONTROLLER', ok: true },
  { text: '   IRQ2: CASCADE CONTROLLER', ok: true },
  { text: '   IRQ6: FLOPPY DISK CONTROLLER', ok: true },
  { text: '   IRQ14: PRIMARY IDE CONTROLLER', ok: true },
  { text: 'SCANNING PCI BUS', dots: true, ok: true },
  { text: '   PCI 0:0:0 HOST BRIDGE', ok: true },
  { text: '   PCI 0:1:0 VGA CONTROLLER', ok: true },
  { text: '   PCI 0:2:0 ETHERNET ADAPTER', ok: true },
  { text: '   PCI 0:3:0 SOUND CONTROLLER', ok: true },
  { text: 'INITIALISING STORAGE SUBSYSTEM', dots: true, ok: true },
  { text: '   IDE CHANNEL 0: PRIMARY', ok: true },
  { text: '   IDE CHANNEL 1: SECONDARY', ok: true },
  { text: '   MOUNTING /DEV/HDA1 AS ROOT', dots: true, ok: true },
  { text: '   MOUNTING /DEV/HDA2 AS SWAP', dots: true, ok: true },
  { text: '   CHECKING FILESYSTEM INTEGRITY', dots: true, ok: true },
  { text: 'LOADING SECURITY MODULE', dots: true, ok: true },
  { text: '   VERIFYING KERNEL SIGNATURE', dots: true, ok: true },
  { text: '   LOADING ACCESS CONTROL LISTS', dots: true, ok: true },
  { text: '   INITIALISING CRYPTO ENGINE', dots: true, ok: true },
  { text: 'ESTABLISHING NETWORK INTERFACES', dots: true, ok: true },
  { text: '   ETH0: 00:1A:2B:3C:4D:5E', ok: true },
  { text: '   LO:   127.0.0.1', ok: true },
  { text: '   CONFIGURING ROUTING TABLE', dots: true, ok: true },
  { text: '   RESOLVING DNS SERVERS', dots: true, ok: true },
  { text: 'CONTACTING A.D.M.N. RELAY NODE', dots: true, ok: true },
  { text: '   AUTHENTICATING SESSION KEY', dots: true, ok: true },
  { text: '   VERIFYING NODE CERTIFICATE', dots: true, ok: true },
  { text: '   SYNCHRONISING GRID MANIFEST', dots: true, ok: true },
  { text: '   GRID STATUS: ONLINE', ok: true },
  { text: 'LOADING SYSTEM DAEMONS', dots: true },
  { text: '   SYSD: PROCESS MANAGER', ok: true },
  { text: '   LOGD: EVENT LOGGER', ok: true },
  { text: '   NETD: NETWORK DAEMON', ok: true },
  { text: '   AUTHD: AUTHENTICATION SERVICE', ok: true },
  { text: '   CROND: TASK SCHEDULER', ok: true },
  { text: 'RUNNING SYSTEM DIAGNOSTICS', dots: true, ok: true },
  { text: '   CPU STRESS TEST', dots: true, ok: true },
  { text: '   MEMORY INTEGRITY CHECK', dots: true, ok: true },
  { text: '   DISK READ/WRITE BENCHMARK', dots: true, ok: true },
  { text: 'SYSTEM DIAGNOSTICS PASSED' },
  { text: '' },
  { text: 'ALL SUBSYSTEMS NOMINAL' },
  { text: '' },
  { text: 'LOADING ENVIRONMENT', dots: true },
];